blank_issues_enabled: false
contact_links:
  - name: ğŸ“¥ Download Eisenhower
    url: https://github.com/Eisenhower-App/eisenhower-releases/releases/latest
    about: Download the latest release of Eisenhower
  - name: ğŸº Install via Homebrew
    url: https://github.com/Eisenhower-App/homebrew-eisenhower
    about: Install Eisenhower using Homebrew
